Repository dotnet/dotnet-api-docs.ja-jp, pull requests merged in 2019-04, with the labels that each got.

#76 転送エンコード → TransferEncoding
  xml/System.Net/HttpWebRequest.xml
Labels: In Progress

#77 "1 in 96px = =" → "1in==96px"
  xml/System.Windows/FigureLength.xml
Labels: Accepted, Linguistic Suggestion

#79 System.Threading.Tasks.Task.RunSynchronously
  xml/System.Threading.Tasks/Task.xml
Labels: Linguistic Suggestion, Partially Accepted

#80 "constructor" should be translated into "コンストラクター"
  xml/Microsoft.Build.BuildEngine/InvalidToolsetDefinitionException.xml
Labels: Linguistic Suggestion, Partially Accepted
