Repository dotnet/dotnet-api-docs.ja-jp, pull requests merged in 2019-03, with the labels that each got.

#43 Visual c# → Visual C#
  xml/System.AddIn.Contract.Automation/RemoteParameterData.xml
Labels: Linguistic Issue

#42 c# → C#
  xml/System.Web.UI.MobileControls/Alignment.xml
Labels: Accepted, Linguistic Suggestion

#41 c# → C#
  xml/System.Threading/Monitor.xml
Labels: Accepted, Linguistic Suggestion

#40 c# → C#
  xml/System.Runtime.InteropServices/InAttribute.xml
Labels: Accepted, Linguistic Suggestion

#48 Visual c# → Visual C#
  xml/System.Data/EnumerableRowCollectionExtensions.xml
Labels: Accepted

#45 接続 → Connection
  xml/System.Net/HttpWebRequest.xml
Labels: Accepted

#44 そのまま使用します。→ Accept
  xml/System.Net/HttpWebRequest.xml
Labels: Accepted, Linguistic Suggestion

#50 Visual c# → Visual C#
  xml/System.Data.SqlClient/SqlCommand.xml
Labels: Accepted

#53 Visual c# → Visual C#
  xml/System.Linq/Enumerable.xml
Labels: Accepted

#51 Visual c# → Visual C#
  xml/System.Data.OracleClient/OracleParameter.xml
Labels: Accepted

#62 Visual c# → Visual C#
  xml/System.Runtime.InteropServices/DefaultParameterValueAttribute.xml
Labels: Accepted

#57 Visual c# → Visual C#, Visual basic → Visual Basic
  xml/System.Reflection/AssemblyKeyFileAttribute.xml
Labels: Accepted

#61 Visual c# → Visual C#
  xml/System.Runtime.CompilerServices/UnsafeValueTypeAttribute.xml
Labels: Accepted

#56 Visual c# → Visual C#
  xml/System.Linq/Lookup`2.xml
Labels: Accepted

#55 Visual c# → Visual C#
  xml/System.Linq/IGrouping`2.xml
Labels: Accepted

#63 Visual c# → Visual C#
  xml/System.Xml/XmlTextWriter.xml
Labels: Linguistic Suggestion

#64 Update ResourceManager.xml
  xml/System.Resources/ResourceManager.xml
Labels: Linguistic Suggestion, Partially Accepted

#66 予想されます。 → Expect
  xml/System.Net/HttpWebRequest.xml
Labels: Accepted, Linguistic Suggestion

#65 コンテンツの長さ → ContentLength
  xml/System.Net/HttpWebRequest.xml
Labels: Accepted, Linguistic Suggestion

#67 Button.IsDefault
  xml/System.Windows.Controls/Button.xml
Labels: Accepted, Linguistic Suggestion

#68 Button.IsDefaulted
  xml/System.Windows.Controls/Button.xml
Labels: Linguistic Suggestion, Partially Accepted

#69 日付 → Date
  xml/System.Net/HttpWebRequest.xml
Labels: Accepted, Linguistic Suggestion
