Repository dotnet/dotnet-api-docs.ja-jp, pull requests merged in 2019-01, with the labels that each got.

#21 c# → C#
  xml/System/Boolean.xml
Labels: Accepted, Linguistic Suggestion

#17 Update DeflateStream.xml
  xml/System.IO.Compression/DeflateStream.xml
Labels: In Progress, Linguistic Suggestion

#22 Api → API
  xml/ns-System.Net.PeerToPeer.Collaboration.xml
Labels: Accepted, Linguistic Suggestion

#23 "nt。 $" → "nt.$"
  xml/System.Net/HttpWebRequest.xml
Labels: Accepted, Linguistic Suggestion

#28 c# → C#
  xml/ns-System.xml
Labels: Accepted, Linguistic Suggestion

#27 c# → C#
  xml/Microsoft.VisualBasic/VBCodeProvider.xml
Labels: Linguistic Suggestion

#31 Linguistic Suggestion
  xml/System.Reflection/AssemblyVersionAttribute.xml
Labels: Accepted, Linguistic Suggestion
