Repository dotnet/dotnet-api-docs.ja-jp, pull requests merged in 2019-02, with the labels that each got.

#15 Retranslated System.windows.UIElement.Focus
  xml/System.Windows/UIElement.xml
Labels: Accepted, Linguistic Suggestion, Source Issue

#34 組オブジェクト → タプルオブジェクト
  xml/System.Collections/IStructuralComparable.xml
Labels: Accepted With Changes, Linguistic Suggestion

#35 Update Process.xml
  xml/System.Diagnostics/Process.xml
Labels: Accepted With Changes, Linguistic Suggestion

#36 c# → C#
  xml/System.Runtime.CompilerServices/RuntimeWrappedException.xml
Labels: Accepted, Linguistic Suggestion

#38 c# → C#
  xml/System.Runtime.CompilerServices/RuntimeCompatibilityAttribute.xml
Labels: Accepted, Linguistic Suggestion
